trigger: generate_pr_description # <-- ðŸ‘‹ pick a trigger
title: Generate PR Description   # <-- ðŸ‘‹ pick a title

surfaces:
   - pull_request

description: Generate a PR Description using Generative AI
steps:
  # This displays a menu, similar to typing `@`.
  # - type: menu
  #   id: some_options
  #   label: Options
  #   options:
  #     - Item 1
  #     - Item 2
  #     - Item 3
  # This displays a form with a dropdown, text input, and markdown editor.
  # - type: form
  #   style: modal
  #   body:
  #     - type: dropdown
  #       attributes:
  #         label: Priority
  #         options:
  #         - label: "ðŸŸ¢ Normal"
  #         - label: "âš ï¸ Important"
  #         - label: "ðŸ’¥ Emergency"
  #     - type: input
  #       attributes:
  #         label: Name
  #         format: text
  #     - type: textarea
  #       attributes:
  #         label: Message
  #         placeholder: What happened?
  # You can use slash commands to run GitHub Actions using repository_dispatch.
  # Any input provided to menus or forms will be available from your workflow.
  - type: repository_dispatch
    eventType: pull_request
  # You can insert markdown into the markdown editor. The template property is
  # processed as a Liquid template.
  - type: fill
    template: |-
      Generating PR description...
      Here is the data you provided: {{data}}
      And here is some information about the command: {{command}}
