name: Generate PR Description
on: workflow_dispatch
jobs: 
  call-api: 
    runs-on: ubuntu-latest
    steps:
      - name: Call PR Generation API
        id: request
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://us-central1-alert-vim-413707.cloudfunctions.net/generate_pr_description'
          method: 'POST'
          preventFailureOnNoResponse: true
          # bearerToken: ${{ secrets.BEARER_TOKEN }}
          # customHeaders: '{"Content-Type": "application/json"}'
          timeout: 60000
          data: '{"git_repo_url": "${{ github.server_url}}/${{github.repository }}", "base_branch_name": "${{ github.head_ref }}", "branch_name" : "${{ github.ref_name }}"}'
      - name: Show Response
        run: |
          echo ${{ steps.request.outputs.response }}
          echo ${{ steps.request.outputs.headers }}
