name: Generate PR Description
on: 
  pull_request:
    types: [opened]
jobs: 
  call-api: 
    runs-on: ubuntu-latest
    steps:
      - name: Log event
        run: echo "${{ toJSON(github) }}"
      - name: Call PR Generation API
        id: request
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://us-central1-alert-vim-413707.cloudfunctions.net/generate_pr_description'
          method: 'POST'
          preventFailureOnNoResponse: true
          # bearerToken: ${{ secrets.BEARER_TOKEN }}
          # customHeaders: '{"Content-Type": "application/json"}'
          timeout: 60000
          data: '{"git_repo_url": "${{ github.server_url}}/${{github.repository }}", "base_branch_name": "${{ github.event.repository.default_branch }}", "branch_name" : "${{ github.ref_name }}"}'
      - name: Show Response
        run: |
          echo ${{ steps.request.outputs.response }}
          echo ${{ steps.request.outputs.headers }}
      - name: Post Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
