name: Generate PR Description
on: 
  pull_request:
    types: [opened]
jobs: 
  call-api: 
    runs-on: ubuntu-latest
    steps:
      - name: Log event
        run: echo "${{ toJSON(github) }}"
      - name: Call PR Generation API
        id: request
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://us-central1-alert-vim-413707.cloudfunctions.net/generate_pr_description'
          method: 'POST'
          preventFailureOnNoResponse: true
          # bearerToken: ${{ secrets.BEARER_TOKEN }}
          # customHeaders: '{"Content-Type": "application/json"}'
          timeout: 60000
          data: '{"git_repo_url": "${{ github.server_url}}/${{github.repository }}", "base_branch_name": "${{ github.base_ref }}", "branch_name" : "${{ github.head_ref }}"}'
      - name: Show Response
        run: |
          echo ${{ steps.request.outputs.response }}
          echo ${{ steps.request.outputs.headers }}
      - name: Post Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{github.event.number}}
          body: |
            🤖 Here is a suggestion for the Pull Request description, generated by AI:
            
            ${{ steps.reqest.outputs.response }}
